FROM wordpress:6.2-fpm

MAINTAINER Quentin Jungo <qjungo@student.42lausanne.ch>

# Install dependencies
RUN sudo apt update
RUN sudo apt install \
						apache2 \
						ghostscript \
						libapache2-mod-php \
						mysql-server \
						php \
						php-bcmath \
						php-curl \
						php-imagick \
						php-intl \
						php-json \
						php-mbstring \
						php-mysql \
						php-xml \
						php-zip
